### ISSUE TITLE
gymnasium_basic_usage.py | Problem running it

### ISSUE THREAD

**Issue by valgau-asu** [spencerfolk/rotorpy#11]
Hi, I recently installed RotorPy (Running on Windows | Python 3.11.9) and wanted to use the RL/ML features you propose.
I tried to run "gymnasium_basic_usage.py" and got the following error:

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
PS D:\Documents\ASU\RotorPy\rotorpy\examples> python .\gymnasium_basic_usage.py
Traceback (most recent call last):
  File "D:\Documents\ASU\RotorPy\rotorpy\examples\gymnasium_basic_usage.py", line 51, in <module>
    observation, info = env.reset(initial_state='random')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: OrderEnforcing.reset() got an unexpected keyword argument 'initial_state'
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

Do you have any idea from where this could come from?

Thanks,

Val

**Comment by RoboDD** [comment]
Same Issue:

Traceback (most recent call last):
  File "ppo_hover_train.py", line 62, in <module>
    observation, info = env.reset(initial_state='random', options={'pos_bound': 2, 'vel_bound': 0})
TypeError: reset() got an unexpected keyword argument 'initial_state'

**Comment by spencerfolk** [comment]
Thanks for bringing this to my attention. @valgau-asu or @RoboDD can you tell me what versions of gymnasium you're running?

**Comment by RoboDD** [comment]
> Thanks for bringing this to my attention. @valgau-asu or @RoboDD can you tell me what versions of gymnasium you're running?

Hi @spencerfolk,

Thanks for quick reply. My versions of gymnasium is 1.0.0.

```
~/rotorpy/examples$ python
Python 3.8.10 (default, Jul 29 2024, 17:02:10)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gymnasium
>>> gymnasium.__version__
'1.0.0'
```

**Comment by spencerfolk** [comment]
Ok I was able to replicate the error by upgrading to `gymnasium==1.0.0`. I suspect they might have changed some things since the initial version I installed when developing the gym environment. 

As a band-aid solution I specified a compatible version of `gymnasium` in the `setup.py`. You can see the version in 93394853114c358005878f2306bbd9c433b4abf9

It's older but still has the main functionality offered by the `gymnasium` package. 

I'm going to keep this issue open because I'd like to one day make the environment compatible with future versions of `gymnasium`. If anyone figures out the future-proof fix feel free to open a PR.

**Comment by RoboDD** [comment]
My temporal solution:

`ppo_hover_train.py`, modify these lines:

```python
# Reset the environment
# observation, info = env.reset(initial_state='random', options={'pos_bound': 2, 'vel_bound': 0})
observation, info = env.reset(options={'initial_state': 'random', 'pos_bound': 2, 'vel_bound': 1})
```

`quadrotor_enviroments.py`, modify these lines:

```python
def reset(self, seed=None, options={'initial_state':'random', 'pos_bound': 2, 'vel_bound': 0}):
...............
        #! add two lines to force assign parameter after super().reset(seed=seed)
        options={'initial_state':'random', 'pos_bound': 2, 'vel_bound': 0}
        initial_state = 'random'
...............
```

Then, I can run the given PPO train and eval scripts. It seems `reset` function can not have `initial_state` as an argument.

**Comment by valgau-asu** [comment]
Thank you for the answer! It worked on my end.

**Comment by spencerfolk** [comment]
I made the recommended changes in 68ad76472732a6a98c03ef8442f12e95801f723b. Thanks for pointing this out!
